// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008113346_CreateGreenLifeSupermarket")]
    partial class CreateGreenLifeSupermarket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Thực phẩm hữu cơ",
                            Description = "Các sản phẩm thực phẩm hữu cơ, tự nhiên"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Đồ uống thiên nhiên",
                            Description = "Nước uống, trà và các sản phẩm có nguồn gốc tự nhiên"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sản phẩm chăm sóc cá nhân",
                            Description = "Các sản phẩm chăm sóc cá nhân thân thiện với môi trường"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Đồ dùng gia đình xanh",
                            Description = "Đồ dùng gia đình có thể tái sử dụng"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Sản phẩm tái chế",
                            Description = "Các sản phẩm được làm từ vật liệu tái chế"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Rau củ hữu cơ",
                            Description = "Các loại rau củ được trồng theo phương pháp hữu cơ"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Trái cây hữu cơ",
                            Description = "Các loại trái cây sạch và tự nhiên"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Ngũ cốc",
                            Description = "Các loại ngũ cốc và hạt dinh dưỡng"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Thực phẩm khô",
                            Description = "Các loại thực phẩm khô tiện dụng"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Gia vị tự nhiên",
                            Description = "Các loại gia vị có nguồn gốc tự nhiên"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Đồ dùng nhà bếp",
                            Description = "Các sản phẩm sử dụng trong nhà bếp"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Đồ dùng cá nhân",
                            Description = "Các sản phẩm phục vụ nhu cầu cá nhân"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Văn phòng phẩm xanh",
                            Description = "Văn phòng phẩm thân thiện với môi trường"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Sản phẩm vệ sinh",
                            Description = "Các sản phẩm vệ sinh an toàn"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Sản phẩm thân thiện môi trường",
                            Description = "Các sản phẩm góp phần bảo vệ môi trường"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "TP. Hồ Chí Minh",
                            Email = "nguyenvanan@gmail.com",
                            FullName = "Nguyễn Văn An",
                            PhoneNumber = "0900000001"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "TP. Hồ Chí Minh",
                            Email = "tranthibinh@gmail.com",
                            FullName = "Trần Thị Bình",
                            PhoneNumber = "0900000002"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Bình Dương",
                            Email = "levancuong@gmail.com",
                            FullName = "Lê Văn Cường",
                            PhoneNumber = "0900000003"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Đồng Nai",
                            Email = "phamthidung@gmail.com",
                            FullName = "Phạm Thị Dung",
                            PhoneNumber = "0900000004"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "TP. Hồ Chí Minh",
                            Email = "hoangvanminh@gmail.com",
                            FullName = "Hoàng Văn Minh",
                            PhoneNumber = "0900000005"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Long An",
                            Email = "nguyenthilan@gmail.com",
                            FullName = "Nguyễn Thị Lan",
                            PhoneNumber = "0900000006"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "TP. Hồ Chí Minh",
                            Email = "tranvanhung@gmail.com",
                            FullName = "Trần Văn Hùng",
                            PhoneNumber = "0900000007"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Bình Dương",
                            Email = "lethimai@gmail.com",
                            FullName = "Lê Thị Mai",
                            PhoneNumber = "0900000008"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Đồng Nai",
                            Email = "phamvannam@gmail.com",
                            FullName = "Phạm Văn Nam",
                            PhoneNumber = "0900000009"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "TP. Hồ Chí Minh",
                            Email = "hoangthihoa@gmail.com",
                            FullName = "Hoàng Thị Hoa",
                            PhoneNumber = "0900000010"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Tây Ninh",
                            Email = "dovanthanh@gmail.com",
                            FullName = "Đỗ Văn Thành",
                            PhoneNumber = "0900000011"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "TP. Hồ Chí Minh",
                            Email = "vuthihuong@gmail.com",
                            FullName = "Vũ Thị Hương",
                            PhoneNumber = "0900000012"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Bà Rịa - Vũng Tàu",
                            Email = "nguyenvanlong@gmail.com",
                            FullName = "Nguyễn Văn Long",
                            PhoneNumber = "0900000013"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "TP. Hồ Chí Minh",
                            Email = "tranthingoc@gmail.com",
                            FullName = "Trần Thị Ngọc",
                            PhoneNumber = "0900000014"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Bình Phước",
                            Email = "levanphuc@gmail.com",
                            FullName = "Lê Văn Phúc",
                            PhoneNumber = "0900000015"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 205000m,
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 115000m,
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 10, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 165000m,
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 10, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 95000m,
                            UserId = 3
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 110000m,
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 6,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 10, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 88000m,
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 7,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 10, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 170000m,
                            UserId = 3
                        },
                        new
                        {
                            OrderId = 8,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 10, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 165000m,
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 9,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 10, 6, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 185000m,
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 10,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 10, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalAmount = 195000m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            TotalPrice = 85000m,
                            UnitPrice = 85000m
                        },
                        new
                        {
                            OrderDetailId = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            TotalPrice = 120000m,
                            UnitPrice = 120000m
                        },
                        new
                        {
                            OrderDetailId = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 2,
                            TotalPrice = 70000m,
                            UnitPrice = 35000m
                        },
                        new
                        {
                            OrderDetailId = 4,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 1,
                            TotalPrice = 45000m,
                            UnitPrice = 45000m
                        },
                        new
                        {
                            OrderDetailId = 5,
                            OrderId = 3,
                            ProductId = 5,
                            Quantity = 1,
                            TotalPrice = 55000m,
                            UnitPrice = 55000m
                        },
                        new
                        {
                            OrderDetailId = 6,
                            OrderId = 3,
                            ProductId = 6,
                            Quantity = 1,
                            TotalPrice = 110000m,
                            UnitPrice = 110000m
                        },
                        new
                        {
                            OrderDetailId = 7,
                            OrderId = 4,
                            ProductId = 7,
                            Quantity = 1,
                            TotalPrice = 45000m,
                            UnitPrice = 45000m
                        },
                        new
                        {
                            OrderDetailId = 8,
                            OrderId = 4,
                            ProductId = 8,
                            Quantity = 2,
                            TotalPrice = 50000m,
                            UnitPrice = 25000m
                        },
                        new
                        {
                            OrderDetailId = 9,
                            OrderId = 5,
                            ProductId = 9,
                            Quantity = 1,
                            TotalPrice = 35000m,
                            UnitPrice = 35000m
                        },
                        new
                        {
                            OrderDetailId = 10,
                            OrderId = 5,
                            ProductId = 10,
                            Quantity = 1,
                            TotalPrice = 75000m,
                            UnitPrice = 75000m
                        },
                        new
                        {
                            OrderDetailId = 11,
                            OrderId = 6,
                            ProductId = 11,
                            Quantity = 2,
                            TotalPrice = 60000m,
                            UnitPrice = 30000m
                        },
                        new
                        {
                            OrderDetailId = 12,
                            OrderId = 6,
                            ProductId = 12,
                            Quantity = 1,
                            TotalPrice = 28000m,
                            UnitPrice = 28000m
                        },
                        new
                        {
                            OrderDetailId = 13,
                            OrderId = 7,
                            ProductId = 13,
                            Quantity = 2,
                            TotalPrice = 130000m,
                            UnitPrice = 65000m
                        },
                        new
                        {
                            OrderDetailId = 14,
                            OrderId = 7,
                            ProductId = 14,
                            Quantity = 1,
                            TotalPrice = 40000m,
                            UnitPrice = 40000m
                        },
                        new
                        {
                            OrderDetailId = 15,
                            OrderId = 8,
                            ProductId = 15,
                            Quantity = 1,
                            TotalPrice = 90000m,
                            UnitPrice = 90000m
                        },
                        new
                        {
                            OrderDetailId = 16,
                            OrderId = 8,
                            ProductId = 16,
                            Quantity = 1,
                            TotalPrice = 75000m,
                            UnitPrice = 75000m
                        },
                        new
                        {
                            OrderDetailId = 17,
                            OrderId = 9,
                            ProductId = 19,
                            Quantity = 2,
                            TotalPrice = 90000m,
                            UnitPrice = 45000m
                        },
                        new
                        {
                            OrderDetailId = 18,
                            OrderId = 9,
                            ProductId = 21,
                            Quantity = 1,
                            TotalPrice = 95000m,
                            UnitPrice = 95000m
                        },
                        new
                        {
                            OrderDetailId = 19,
                            OrderId = 10,
                            ProductId = 29,
                            Quantity = 1,
                            TotalPrice = 15000m,
                            UnitPrice = 15000m
                        },
                        new
                        {
                            OrderDetailId = 20,
                            OrderId = 10,
                            ProductId = 30,
                            Quantity = 1,
                            TotalPrice = 180000m,
                            UnitPrice = 180000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "893000000001",
                            CategoryId = 1,
                            Price = 85000m,
                            ProductName = "Gạo lứt hữu cơ",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "893000000002",
                            CategoryId = 1,
                            Price = 120000m,
                            ProductName = "Mật ong nguyên chất",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "893000000003",
                            CategoryId = 2,
                            Price = 35000m,
                            ProductName = "Nước ép cam nguyên chất",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "893000000004",
                            CategoryId = 2,
                            Price = 45000m,
                            ProductName = "Trà xanh thiên nhiên",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "893000000005",
                            CategoryId = 3,
                            Price = 55000m,
                            ProductName = "Xà phòng thiên nhiên",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "893000000006",
                            CategoryId = 3,
                            Price = 110000m,
                            ProductName = "Dầu gội thảo mộc",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "893000000007",
                            CategoryId = 4,
                            Price = 45000m,
                            ProductName = "Túi vải tái sử dụng",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "893000000008",
                            CategoryId = 4,
                            Price = 25000m,
                            ProductName = "Ống hút tre",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "893000000009",
                            CategoryId = 5,
                            Price = 35000m,
                            ProductName = "Sổ tay giấy tái chế",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "893000000010",
                            CategoryId = 5,
                            Price = 75000m,
                            ProductName = "Chậu cây nhựa tái chế",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "893000000011",
                            CategoryId = 6,
                            Price = 30000m,
                            ProductName = "Cải xanh hữu cơ",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "893000000012",
                            CategoryId = 6,
                            Price = 28000m,
                            ProductName = "Cà rốt hữu cơ",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "893000000013",
                            CategoryId = 7,
                            Price = 65000m,
                            ProductName = "Táo hữu cơ",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "893000000014",
                            CategoryId = 7,
                            Price = 40000m,
                            ProductName = "Chuối hữu cơ",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "893000000015",
                            CategoryId = 8,
                            Price = 90000m,
                            ProductName = "Yến mạch nguyên hạt",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "893000000016",
                            CategoryId = 8,
                            Price = 75000m,
                            ProductName = "Hạt chia",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "893000000017",
                            CategoryId = 9,
                            Price = 95000m,
                            ProductName = "Nấm hương khô",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "893000000018",
                            CategoryId = 9,
                            Price = 70000m,
                            ProductName = "Mộc nhĩ khô",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "893000000019",
                            CategoryId = 10,
                            Price = 20000m,
                            ProductName = "Muối biển tự nhiên",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "893000000020",
                            CategoryId = 10,
                            Price = 45000m,
                            ProductName = "Tiêu đen hữu cơ",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "893000000021",
                            CategoryId = 11,
                            Price = 95000m,
                            ProductName = "Hộp đựng thực phẩm thủy tinh",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "893000000022",
                            CategoryId = 11,
                            Price = 25000m,
                            ProductName = "Muỗng tre",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "893000000023",
                            CategoryId = 12,
                            Price = 40000m,
                            ProductName = "Khăn tay cotton",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "893000000024",
                            CategoryId = 12,
                            Price = 85000m,
                            ProductName = "Bình nước cá nhân",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 25,
                            Barcode = "893000000025",
                            CategoryId = 13,
                            Price = 35000m,
                            ProductName = "Sổ tay tái chế",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 26,
                            Barcode = "893000000026",
                            CategoryId = 13,
                            Price = 15000m,
                            ProductName = "Bút thân thiện môi trường",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 27,
                            Barcode = "893000000027",
                            CategoryId = 14,
                            Price = 65000m,
                            ProductName = "Nước lau sàn sinh học",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 28,
                            Barcode = "893000000028",
                            CategoryId = 14,
                            Price = 60000m,
                            ProductName = "Nước rửa chén sinh học",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 29,
                            Barcode = "893000000029",
                            CategoryId = 15,
                            Price = 15000m,
                            ProductName = "Túi giấy thân thiện môi trường",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 30,
                            Barcode = "893000000030",
                            CategoryId = 15,
                            Price = 180000m,
                            ProductName = "Bình giữ nhiệt inox",
                            StockQuantity = 25
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Quản trị viên",
                            IsActive = true,
                            Password = "123456",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            FullName = "Nguyễn Văn Thuận",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier1"
                        },
                        new
                        {
                            UserId = 3,
                            FullName = "Trần Văn Nam",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier2"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderDetail", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
