// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008122638_CreateGreenLifeSupermarket")]
    partial class CreateGreenLifeSupermarket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDonHang"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietDonHang");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietDonHang");

                    b.HasData(
                        new
                        {
                            MaChiTietDonHang = 1,
                            DonGia = 85000m,
                            MaDonHang = 1,
                            MaSanPham = 1,
                            SoLuong = 1,
                            ThanhTien = 85000m
                        },
                        new
                        {
                            MaChiTietDonHang = 2,
                            DonGia = 120000m,
                            MaDonHang = 1,
                            MaSanPham = 2,
                            SoLuong = 1,
                            ThanhTien = 120000m
                        },
                        new
                        {
                            MaChiTietDonHang = 3,
                            DonGia = 35000m,
                            MaDonHang = 2,
                            MaSanPham = 3,
                            SoLuong = 2,
                            ThanhTien = 70000m
                        },
                        new
                        {
                            MaChiTietDonHang = 4,
                            DonGia = 45000m,
                            MaDonHang = 2,
                            MaSanPham = 4,
                            SoLuong = 1,
                            ThanhTien = 45000m
                        },
                        new
                        {
                            MaChiTietDonHang = 5,
                            DonGia = 55000m,
                            MaDonHang = 3,
                            MaSanPham = 5,
                            SoLuong = 1,
                            ThanhTien = 55000m
                        },
                        new
                        {
                            MaChiTietDonHang = 6,
                            DonGia = 110000m,
                            MaDonHang = 3,
                            MaSanPham = 6,
                            SoLuong = 1,
                            ThanhTien = 110000m
                        },
                        new
                        {
                            MaChiTietDonHang = 7,
                            DonGia = 45000m,
                            MaDonHang = 4,
                            MaSanPham = 7,
                            SoLuong = 1,
                            ThanhTien = 45000m
                        },
                        new
                        {
                            MaChiTietDonHang = 8,
                            DonGia = 25000m,
                            MaDonHang = 4,
                            MaSanPham = 8,
                            SoLuong = 2,
                            ThanhTien = 50000m
                        },
                        new
                        {
                            MaChiTietDonHang = 9,
                            DonGia = 35000m,
                            MaDonHang = 5,
                            MaSanPham = 9,
                            SoLuong = 1,
                            ThanhTien = 35000m
                        },
                        new
                        {
                            MaChiTietDonHang = 10,
                            DonGia = 75000m,
                            MaDonHang = 5,
                            MaSanPham = 10,
                            SoLuong = 1,
                            ThanhTien = 75000m
                        },
                        new
                        {
                            MaChiTietDonHang = 11,
                            DonGia = 30000m,
                            MaDonHang = 6,
                            MaSanPham = 11,
                            SoLuong = 2,
                            ThanhTien = 60000m
                        },
                        new
                        {
                            MaChiTietDonHang = 12,
                            DonGia = 28000m,
                            MaDonHang = 6,
                            MaSanPham = 12,
                            SoLuong = 1,
                            ThanhTien = 28000m
                        },
                        new
                        {
                            MaChiTietDonHang = 13,
                            DonGia = 65000m,
                            MaDonHang = 7,
                            MaSanPham = 13,
                            SoLuong = 2,
                            ThanhTien = 130000m
                        },
                        new
                        {
                            MaChiTietDonHang = 14,
                            DonGia = 40000m,
                            MaDonHang = 7,
                            MaSanPham = 14,
                            SoLuong = 1,
                            ThanhTien = 40000m
                        },
                        new
                        {
                            MaChiTietDonHang = 15,
                            DonGia = 90000m,
                            MaDonHang = 8,
                            MaSanPham = 15,
                            SoLuong = 1,
                            ThanhTien = 90000m
                        },
                        new
                        {
                            MaChiTietDonHang = 16,
                            DonGia = 75000m,
                            MaDonHang = 8,
                            MaSanPham = 16,
                            SoLuong = 1,
                            ThanhTien = 75000m
                        },
                        new
                        {
                            MaChiTietDonHang = 17,
                            DonGia = 45000m,
                            MaDonHang = 9,
                            MaSanPham = 19,
                            SoLuong = 2,
                            ThanhTien = 90000m
                        },
                        new
                        {
                            MaChiTietDonHang = 18,
                            DonGia = 95000m,
                            MaDonHang = 9,
                            MaSanPham = 21,
                            SoLuong = 1,
                            ThanhTien = 95000m
                        },
                        new
                        {
                            MaChiTietDonHang = 19,
                            DonGia = 15000m,
                            MaDonHang = 10,
                            MaSanPham = 29,
                            SoLuong = 1,
                            ThanhTien = 15000m
                        },
                        new
                        {
                            MaChiTietDonHang = 20,
                            DonGia = 180000m,
                            MaDonHang = 10,
                            MaSanPham = 30,
                            SoLuong = 1,
                            ThanhTien = 180000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DonHang");

                    b.HasData(
                        new
                        {
                            MaDonHang = 1,
                            MaKhachHang = 1,
                            MaNguoiDung = 1,
                            NgayDatHang = new DateTime(2026, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 205000m,
                            TrangThai = "Completed"
                        },
                        new
                        {
                            MaDonHang = 2,
                            MaKhachHang = 2,
                            MaNguoiDung = 2,
                            NgayDatHang = new DateTime(2026, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 115000m,
                            TrangThai = "Completed"
                        },
                        new
                        {
                            MaDonHang = 3,
                            MaKhachHang = 3,
                            MaNguoiDung = 2,
                            NgayDatHang = new DateTime(2026, 10, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 165000m,
                            TrangThai = "Completed"
                        },
                        new
                        {
                            MaDonHang = 4,
                            MaKhachHang = 4,
                            MaNguoiDung = 3,
                            NgayDatHang = new DateTime(2026, 10, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 95000m,
                            TrangThai = "Completed"
                        },
                        new
                        {
                            MaDonHang = 5,
                            MaKhachHang = 5,
                            MaNguoiDung = 1,
                            NgayDatHang = new DateTime(2026, 10, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 110000m,
                            TrangThai = "Completed"
                        },
                        new
                        {
                            MaDonHang = 6,
                            MaKhachHang = 1,
                            MaNguoiDung = 2,
                            NgayDatHang = new DateTime(2026, 10, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 88000m,
                            TrangThai = "Completed"
                        },
                        new
                        {
                            MaDonHang = 7,
                            MaKhachHang = 2,
                            MaNguoiDung = 3,
                            NgayDatHang = new DateTime(2026, 10, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 170000m,
                            TrangThai = "Completed"
                        },
                        new
                        {
                            MaDonHang = 8,
                            MaKhachHang = 3,
                            MaNguoiDung = 1,
                            NgayDatHang = new DateTime(2026, 10, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 165000m,
                            TrangThai = "Completed"
                        },
                        new
                        {
                            MaDonHang = 9,
                            MaKhachHang = 4,
                            MaNguoiDung = 2,
                            NgayDatHang = new DateTime(2026, 10, 6, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 185000m,
                            TrangThai = "Completed"
                        },
                        new
                        {
                            MaDonHang = 10,
                            MaKhachHang = 5,
                            MaNguoiDung = 3,
                            NgayDatHang = new DateTime(2026, 10, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 195000m,
                            TrangThai = "Completed"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            MaKhachHang = 1,
                            DiaChi = "25, đường Nguyễn Văn Cừ, phường Nguyễn Cư Trinh, quận 1, Thành phố Hồ Chí Minh",
                            Email = "nguyenvanan@gmail.com",
                            HoTen = "Nguyễn Văn An",
                            SoDienThoai = "0900000001"
                        },
                        new
                        {
                            MaKhachHang = 2,
                            DiaChi = "18, đường Lê Lợi, phường Bến Nghé, quận 1, Thành phố Hồ Chí Minh",
                            Email = "tranthibinh@gmail.com",
                            HoTen = "Trần Thị Bình",
                            SoDienThoai = "0900000002"
                        },
                        new
                        {
                            MaKhachHang = 3,
                            DiaChi = "42, đường Phạm Văn Đồng, phường Hiệp Bình Chánh, thành phố Thủ Đức, Thành phố Hồ Chí Minh",
                            Email = "levancuong@gmail.com",
                            HoTen = "Lê Văn Cường",
                            SoDienThoai = "0900000003"
                        },
                        new
                        {
                            MaKhachHang = 4,
                            DiaChi = "76, đường Đồng Khởi, phường Bến Nghé, quận 1, Thành phố Hồ Chí Minh",
                            Email = "phamthidung@gmail.com",
                            HoTen = "Phạm Thị Dung",
                            SoDienThoai = "0900000004"
                        },
                        new
                        {
                            MaKhachHang = 5,
                            DiaChi = "12, đường Nguyễn Trãi, phường Bến Thành, quận 1, Thành phố Hồ Chí Minh",
                            Email = "hoangvanminh@gmail.com",
                            HoTen = "Hoàng Văn Minh",
                            SoDienThoai = "0900000005"
                        },
                        new
                        {
                            MaKhachHang = 6,
                            DiaChi = "35, đường Nguyễn Huệ, phường Bến Nghé, quận 1, Thành phố Hồ Chí Minh",
                            Email = "nguyenthilan@gmail.com",
                            HoTen = "Nguyễn Thị Lan",
                            SoDienThoai = "0900000006"
                        },
                        new
                        {
                            MaKhachHang = 7,
                            DiaChi = "89, đường Xô Viết Nghệ Tĩnh, phường 21, quận Bình Thạnh, Thành phố Hồ Chí Minh",
                            Email = "tranvanhung@gmail.com",
                            HoTen = "Trần Văn Hùng",
                            SoDienThoai = "0900000007"
                        },
                        new
                        {
                            MaKhachHang = 8,
                            DiaChi = "56, đường Võ Văn Ngân, phường Linh Chiểu, thành phố Thủ Đức, Thành phố Hồ Chí Minh",
                            Email = "lethimai@gmail.com",
                            HoTen = "Lê Thị Mai",
                            SoDienThoai = "0900000008"
                        },
                        new
                        {
                            MaKhachHang = 9,
                            DiaChi = "23, đường Nguyễn Văn Linh, phường Tân Phong, quận 7, Thành phố Hồ Chí Minh",
                            Email = "phamvannam@gmail.com",
                            HoTen = "Phạm Văn Nam",
                            SoDienThoai = "0900000009"
                        },
                        new
                        {
                            MaKhachHang = 10,
                            DiaChi = "101, đường Cách Mạng Tháng Tám, phường 7, quận 3, Thành phố Hồ Chí Minh",
                            Email = "hoangthihoa@gmail.com",
                            HoTen = "Hoàng Thị Hoa",
                            SoDienThoai = "0900000010"
                        },
                        new
                        {
                            MaKhachHang = 11,
                            DiaChi = "64, đường Lê Văn Việt, phường Tăng Nhơn Phú A, thành phố Thủ Đức, Thành phố Hồ Chí Minh",
                            Email = "dovanthanh@gmail.com",
                            HoTen = "Đỗ Văn Thành",
                            SoDienThoai = "0900000011"
                        },
                        new
                        {
                            MaKhachHang = 12,
                            DiaChi = "28, đường Hoàng Văn Thụ, phường 4, quận Tân Bình, Thành phố Hồ Chí Minh",
                            Email = "vuthihuong@gmail.com",
                            HoTen = "Vũ Thị Hương",
                            SoDienThoai = "0900000012"
                        },
                        new
                        {
                            MaKhachHang = 13,
                            DiaChi = "45, đường Trần Hưng Đạo, phường Phú Cường, thành phố Thủ Dầu Một, tỉnh Bình Dương",
                            Email = "nguyenvanlong@gmail.com",
                            HoTen = "Nguyễn Văn Long",
                            SoDienThoai = "0900000013"
                        },
                        new
                        {
                            MaKhachHang = 14,
                            DiaChi = "73, đường Điện Biên Phủ, phường Đa Kao, quận 1, Thành phố Hồ Chí Minh",
                            Email = "tranthingoc@gmail.com",
                            HoTen = "Trần Thị Ngọc",
                            SoDienThoai = "0900000014"
                        },
                        new
                        {
                            MaKhachHang = 15,
                            DiaChi = "19, đường Nguyễn Tất Thành, phường Phước Nguyên, thành phố Bà Rịa, tỉnh Bà Rịa - Vũng Tàu",
                            Email = "levanphuc@gmail.com",
                            HoTen = "Lê Văn Phúc",
                            SoDienThoai = "0900000015"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung");

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            DangHoatDong = true,
                            HoTen = "Quản trị viên",
                            MatKhau = "123456",
                            TenDangNhap = "admin",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaNguoiDung = 2,
                            DangHoatDong = true,
                            HoTen = "Nguyễn Văn Thuận",
                            MatKhau = "123456",
                            TenDangNhap = "cashier1",
                            VaiTro = "Cashier"
                        },
                        new
                        {
                            MaNguoiDung = 3,
                            DangHoatDong = true,
                            HoTen = "Trần Văn Nam",
                            MatKhau = "123456",
                            TenDangNhap = "cashier2",
                            VaiTro = "Cashier"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.NhomHang", b =>
                {
                    b.Property<int>("MaNhomHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhomHang"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNhomHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhomHang");

                    b.ToTable("NhomHang");

                    b.HasData(
                        new
                        {
                            MaNhomHang = 1,
                            MoTa = "Các sản phẩm thực phẩm hữu cơ, tự nhiên",
                            TenNhomHang = "Thực phẩm hữu cơ"
                        },
                        new
                        {
                            MaNhomHang = 2,
                            MoTa = "Nước uống, trà và các sản phẩm có nguồn gốc tự nhiên",
                            TenNhomHang = "Đồ uống thiên nhiên"
                        },
                        new
                        {
                            MaNhomHang = 3,
                            MoTa = "Các sản phẩm chăm sóc cá nhân thân thiện với môi trường",
                            TenNhomHang = "Sản phẩm chăm sóc cá nhân"
                        },
                        new
                        {
                            MaNhomHang = 4,
                            MoTa = "Đồ dùng gia đình có thể tái sử dụng",
                            TenNhomHang = "Đồ dùng gia đình xanh"
                        },
                        new
                        {
                            MaNhomHang = 5,
                            MoTa = "Các sản phẩm được làm từ vật liệu tái chế",
                            TenNhomHang = "Sản phẩm tái chế"
                        },
                        new
                        {
                            MaNhomHang = 6,
                            MoTa = "Các loại rau củ được trồng theo phương pháp hữu cơ",
                            TenNhomHang = "Rau củ hữu cơ"
                        },
                        new
                        {
                            MaNhomHang = 7,
                            MoTa = "Các loại trái cây sạch và tự nhiên",
                            TenNhomHang = "Trái cây hữu cơ"
                        },
                        new
                        {
                            MaNhomHang = 8,
                            MoTa = "Các loại ngũ cốc và hạt dinh dưỡng",
                            TenNhomHang = "Ngũ cốc"
                        },
                        new
                        {
                            MaNhomHang = 9,
                            MoTa = "Các loại thực phẩm khô tiện dụng",
                            TenNhomHang = "Thực phẩm khô"
                        },
                        new
                        {
                            MaNhomHang = 10,
                            MoTa = "Các loại gia vị có nguồn gốc tự nhiên",
                            TenNhomHang = "Gia vị tự nhiên"
                        },
                        new
                        {
                            MaNhomHang = 11,
                            MoTa = "Các sản phẩm sử dụng trong nhà bếp",
                            TenNhomHang = "Đồ dùng nhà bếp"
                        },
                        new
                        {
                            MaNhomHang = 12,
                            MoTa = "Các sản phẩm phục vụ nhu cầu cá nhân",
                            TenNhomHang = "Đồ dùng cá nhân"
                        },
                        new
                        {
                            MaNhomHang = 13,
                            MoTa = "Văn phòng phẩm thân thiện với môi trường",
                            TenNhomHang = "Văn phòng phẩm xanh"
                        },
                        new
                        {
                            MaNhomHang = 14,
                            MoTa = "Các sản phẩm vệ sinh an toàn",
                            TenNhomHang = "Sản phẩm vệ sinh"
                        },
                        new
                        {
                            MaNhomHang = 15,
                            MoTa = "Các sản phẩm góp phần bảo vệ môi trường",
                            TenNhomHang = "Sản phẩm thân thiện môi trường"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaNhomHang")
                        .HasColumnType("int");

                    b.Property<string>("MaVach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaNhomHang");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            MaSanPham = 1,
                            GiaBan = 85000m,
                            MaNhomHang = 1,
                            MaVach = "893000000001",
                            SoLuongTon = 50,
                            TenSanPham = "Gạo lứt hữu cơ"
                        },
                        new
                        {
                            MaSanPham = 2,
                            GiaBan = 120000m,
                            MaNhomHang = 1,
                            MaVach = "893000000002",
                            SoLuongTon = 30,
                            TenSanPham = "Mật ong nguyên chất"
                        },
                        new
                        {
                            MaSanPham = 3,
                            GiaBan = 35000m,
                            MaNhomHang = 2,
                            MaVach = "893000000003",
                            SoLuongTon = 60,
                            TenSanPham = "Nước ép cam nguyên chất"
                        },
                        new
                        {
                            MaSanPham = 4,
                            GiaBan = 45000m,
                            MaNhomHang = 2,
                            MaVach = "893000000004",
                            SoLuongTon = 45,
                            TenSanPham = "Trà xanh thiên nhiên"
                        },
                        new
                        {
                            MaSanPham = 5,
                            GiaBan = 55000m,
                            MaNhomHang = 3,
                            MaVach = "893000000005",
                            SoLuongTon = 35,
                            TenSanPham = "Xà phòng thiên nhiên"
                        },
                        new
                        {
                            MaSanPham = 6,
                            GiaBan = 110000m,
                            MaNhomHang = 3,
                            MaVach = "893000000006",
                            SoLuongTon = 25,
                            TenSanPham = "Dầu gội thảo mộc"
                        },
                        new
                        {
                            MaSanPham = 7,
                            GiaBan = 45000m,
                            MaNhomHang = 4,
                            MaVach = "893000000007",
                            SoLuongTon = 70,
                            TenSanPham = "Túi vải tái sử dụng"
                        },
                        new
                        {
                            MaSanPham = 8,
                            GiaBan = 25000m,
                            MaNhomHang = 4,
                            MaVach = "893000000008",
                            SoLuongTon = 80,
                            TenSanPham = "Ống hút tre"
                        },
                        new
                        {
                            MaSanPham = 9,
                            GiaBan = 35000m,
                            MaNhomHang = 5,
                            MaVach = "893000000009",
                            SoLuongTon = 50,
                            TenSanPham = "Sổ tay giấy tái chế"
                        },
                        new
                        {
                            MaSanPham = 10,
                            GiaBan = 75000m,
                            MaNhomHang = 5,
                            MaVach = "893000000010",
                            SoLuongTon = 25,
                            TenSanPham = "Chậu cây nhựa tái chế"
                        },
                        new
                        {
                            MaSanPham = 11,
                            GiaBan = 30000m,
                            MaNhomHang = 6,
                            MaVach = "893000000011",
                            SoLuongTon = 40,
                            TenSanPham = "Cải xanh hữu cơ"
                        },
                        new
                        {
                            MaSanPham = 12,
                            GiaBan = 28000m,
                            MaNhomHang = 6,
                            MaVach = "893000000012",
                            SoLuongTon = 45,
                            TenSanPham = "Cà rốt hữu cơ"
                        },
                        new
                        {
                            MaSanPham = 13,
                            GiaBan = 65000m,
                            MaNhomHang = 7,
                            MaVach = "893000000013",
                            SoLuongTon = 35,
                            TenSanPham = "Táo hữu cơ"
                        },
                        new
                        {
                            MaSanPham = 14,
                            GiaBan = 40000m,
                            MaNhomHang = 7,
                            MaVach = "893000000014",
                            SoLuongTon = 50,
                            TenSanPham = "Chuối hữu cơ"
                        },
                        new
                        {
                            MaSanPham = 15,
                            GiaBan = 90000m,
                            MaNhomHang = 8,
                            MaVach = "893000000015",
                            SoLuongTon = 30,
                            TenSanPham = "Yến mạch nguyên hạt"
                        },
                        new
                        {
                            MaSanPham = 16,
                            GiaBan = 75000m,
                            MaNhomHang = 8,
                            MaVach = "893000000016",
                            SoLuongTon = 35,
                            TenSanPham = "Hạt chia"
                        },
                        new
                        {
                            MaSanPham = 17,
                            GiaBan = 95000m,
                            MaNhomHang = 9,
                            MaVach = "893000000017",
                            SoLuongTon = 25,
                            TenSanPham = "Nấm hương khô"
                        },
                        new
                        {
                            MaSanPham = 18,
                            GiaBan = 70000m,
                            MaNhomHang = 9,
                            MaVach = "893000000018",
                            SoLuongTon = 30,
                            TenSanPham = "Mộc nhĩ khô"
                        },
                        new
                        {
                            MaSanPham = 19,
                            GiaBan = 20000m,
                            MaNhomHang = 10,
                            MaVach = "893000000019",
                            SoLuongTon = 60,
                            TenSanPham = "Muối biển tự nhiên"
                        },
                        new
                        {
                            MaSanPham = 20,
                            GiaBan = 45000m,
                            MaNhomHang = 10,
                            MaVach = "893000000020",
                            SoLuongTon = 50,
                            TenSanPham = "Tiêu đen hữu cơ"
                        },
                        new
                        {
                            MaSanPham = 21,
                            GiaBan = 95000m,
                            MaNhomHang = 11,
                            MaVach = "893000000021",
                            SoLuongTon = 30,
                            TenSanPham = "Hộp đựng thực phẩm thủy tinh"
                        },
                        new
                        {
                            MaSanPham = 22,
                            GiaBan = 25000m,
                            MaNhomHang = 11,
                            MaVach = "893000000022",
                            SoLuongTon = 70,
                            TenSanPham = "Muỗng tre"
                        },
                        new
                        {
                            MaSanPham = 23,
                            GiaBan = 40000m,
                            MaNhomHang = 12,
                            MaVach = "893000000023",
                            SoLuongTon = 45,
                            TenSanPham = "Khăn tay cotton"
                        },
                        new
                        {
                            MaSanPham = 24,
                            GiaBan = 85000m,
                            MaNhomHang = 12,
                            MaVach = "893000000024",
                            SoLuongTon = 40,
                            TenSanPham = "Bình nước cá nhân"
                        },
                        new
                        {
                            MaSanPham = 25,
                            GiaBan = 35000m,
                            MaNhomHang = 13,
                            MaVach = "893000000025",
                            SoLuongTon = 50,
                            TenSanPham = "Sổ tay tái chế"
                        },
                        new
                        {
                            MaSanPham = 26,
                            GiaBan = 15000m,
                            MaNhomHang = 13,
                            MaVach = "893000000026",
                            SoLuongTon = 80,
                            TenSanPham = "Bút thân thiện môi trường"
                        },
                        new
                        {
                            MaSanPham = 27,
                            GiaBan = 65000m,
                            MaNhomHang = 14,
                            MaVach = "893000000027",
                            SoLuongTon = 35,
                            TenSanPham = "Nước lau sàn sinh học"
                        },
                        new
                        {
                            MaSanPham = 28,
                            GiaBan = 60000m,
                            MaNhomHang = 14,
                            MaVach = "893000000028",
                            SoLuongTon = 40,
                            TenSanPham = "Nước rửa chén sinh học"
                        },
                        new
                        {
                            MaSanPham = 29,
                            GiaBan = 15000m,
                            MaNhomHang = 15,
                            MaVach = "893000000029",
                            SoLuongTon = 100,
                            TenSanPham = "Túi giấy thân thiện môi trường"
                        },
                        new
                        {
                            MaSanPham = 30,
                            GiaBan = 180000m,
                            MaNhomHang = 15,
                            MaVach = "893000000030",
                            SoLuongTon = 25,
                            TenSanPham = "Bình giữ nhiệt inox"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.DonHang", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.SanPham", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.NhomHang", "NhomHang")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNhomHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomHang");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.NhomHang", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
